# Generated by Django 4.2.1 on 2023-09-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant_service_details',
            name='time',
        ),
        migrations.AddField(
            model_name='merchant_service_details',
            name='end_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='merchant_service_details',
            name='start_time',
            field=models.TimeField(default='20:00'),
        ),
    ]
