# Generated by Django 4.2.1 on 2023-09-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_merchant_service_details_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_service_details',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
