# Generated by Django 4.2.1 on 2023-09-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_alter_merchant_service_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_service_details',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
