# Generated by Django 4.2.1 on 2023-09-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_merchant_service_details_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant_service_details',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
